# ruff: noqa: E501,UP031
"""wdt completion — generate shell completion scripts.

Usage:
  wdt completion bash
  wdt completion zsh
  wdt completion fish

Pipe the output into the appropriate shell config file:
  wdt completion bash >> ~/.bashrc
  wdt completion zsh  > ~/.zsh/completions/_wdt
  wdt completion fish > ~/.config/fish/completions/wdt.fish
"""

from __future__ import annotations

import click
from rich.console import Console

console = Console()

# Top-level commands — kept in sync with main.py add_command calls.
_TOP = (
    "assemble backend backup build cloud-sync completion config container "
    "dashboard dbus demo disk doctor extensions fleet gpu gui host-exec "
    "images install maintenance monitor net packages performance profiles "
    "publish setup-rootless shell snapshot status storage stream template "
    "tui update upgrade usb winesapos"
)

_BASH = """\
# wdt bash completion  (auto-generated by: wdt completion bash)
_wdt_completion() {
    local cur prev
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local top_cmds="%(top)s"

    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$top_cmds" -- "$cur") )
        return
    fi

    case "$prev" in
        backup)     COMPREPLY=( $(compgen -W "create list delete restore help" -- "$cur") ) ;;
        publish)    COMPREPLY=( $(compgen -W "create list delete help" -- "$cur") ) ;;
        container)  COMPREPLY=( $(compgen -W "start stop list snapshot console export import help" -- "$cur") ) ;;
        net)        COMPREPLY=( $(compgen -W "forward unforward list status nic help" -- "$cur") ) ;;
        nic)        COMPREPLY=( $(compgen -W "add remove list help" -- "$cur") ) ;;
        profiles)   COMPREPLY=( $(compgen -W "list show install diff help" -- "$cur") ) ;;
        config)     COMPREPLY=( $(compgen -W "show init edit path" -- "$cur") ) ;;
        upgrade)    COMPREPLY=( $(compgen -W "check apply help" -- "$cur") ) ;;
        snapshot)   COMPREPLY=( $(compgen -W "create list restore delete help" -- "$cur") ) ;;
        completion) COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") ) ;;
        usb)        COMPREPLY=( $(compgen -W "attach detach list list-host help" -- "$cur") ) ;;
        disk)       COMPREPLY=( $(compgen -W "resize info help" -- "$cur") ) ;;
        fleet)      COMPREPLY=( $(compgen -W "list status start-all stop-all backup-all help" -- "$cur") ) ;;
        images)     COMPREPLY=( $(compgen -W "list active switch check-update help" -- "$cur") ) ;;
        update)     COMPREPLY=( $(compgen -W "check install" -- "$cur") ) ;;
    esac
}
complete -F _wdt_completion wdt
""" % {"top": _TOP}

_ZSH = """\
#compdef wdt
# wdt zsh completion  (auto-generated by: wdt completion zsh)
_wdt() {
    local state
    _arguments '1: :->cmd' '*: :->args'
    case $state in
        cmd)
            _values 'command' \\
%(cmds)s
            ;;
        args)
            case ${words[2]} in
                backup)    _values 'subcommand' create list delete restore help ;;
                publish)   _values 'subcommand' create list delete help ;;
                container) _values 'subcommand' start stop list snapshot console export import help ;;
                net)       _values 'subcommand' forward unforward list status nic help ;;
                profiles)  _values 'subcommand' list show install diff help ;;
                config)    _values 'subcommand' show init edit path ;;
                upgrade)   _values 'subcommand' check apply help ;;
                snapshot)  _values 'subcommand' create list restore delete help ;;
                completion) _values 'shell' bash zsh fish ;;
                usb)       _values 'subcommand' attach detach list list-host help ;;
                disk)      _values 'subcommand' resize info help ;;
                fleet)     _values 'subcommand' list status start-all stop-all backup-all help ;;
                images)    _values 'subcommand' list active switch check-update help ;;
                update)    _values 'subcommand' check install ;;
            esac
            ;;
    esac
}
_wdt
"""

_ZSH_CMDS = "\n".join(
    f"                '{c}[wdt {c}]' \\"
    for c in _TOP.split()
)

_FISH = """\
# wdt fish completion  (auto-generated by: wdt completion fish)
set -l top_cmds %(top)s
complete -c wdt -f -n 'not __fish_seen_subcommand_from $top_cmds' -a "$top_cmds"
complete -c wdt -f -n '__fish_seen_subcommand_from backup'     -a 'create list delete restore help'
complete -c wdt -f -n '__fish_seen_subcommand_from publish'    -a 'create list delete help'
complete -c wdt -f -n '__fish_seen_subcommand_from container'  -a 'start stop list snapshot console export import help'
complete -c wdt -f -n '__fish_seen_subcommand_from net'        -a 'forward unforward list status nic help'
complete -c wdt -f -n '__fish_seen_subcommand_from profiles'   -a 'list show install diff help'
complete -c wdt -f -n '__fish_seen_subcommand_from config'     -a 'show init edit path'
complete -c wdt -f -n '__fish_seen_subcommand_from upgrade'    -a 'check apply help'
complete -c wdt -f -n '__fish_seen_subcommand_from snapshot'   -a 'create list restore delete help'
complete -c wdt -f -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c wdt -f -n '__fish_seen_subcommand_from usb'        -a 'attach detach list list-host help'
complete -c wdt -f -n '__fish_seen_subcommand_from disk'       -a 'resize info help'
complete -c wdt -f -n '__fish_seen_subcommand_from fleet'      -a 'list status start-all stop-all backup-all help'
complete -c wdt -f -n '__fish_seen_subcommand_from images'     -a 'list active switch check-update help'
complete -c wdt -f -n '__fish_seen_subcommand_from update'     -a 'check install'
""" % {"top": _TOP}


@click.command("completion")
@click.argument("shell", type=click.Choice(["bash", "zsh", "fish"]))
def cmd(shell: str) -> None:
    """Generate a shell completion script.

    \b
    Usage:
      wdt completion bash >> ~/.bashrc
      wdt completion zsh  > ~/.zsh/completions/_wdt
      wdt completion fish > ~/.config/fish/completions/wdt.fish
    """
    if shell == "bash":
        click.echo(_BASH, nl=False)
    elif shell == "zsh":
        click.echo(_ZSH % {"cmds": _ZSH_CMDS}, nl=False)
    elif shell == "fish":
        click.echo(_FISH, nl=False)
